'use client';

import Link from 'next/link';
import { Shield, ArrowLeft, Eye, Database, Lock, Globe, UserCheck, Mail, Settings, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { LegalText } from '@/components/common/LegalText';
import { BilingualText } from '@/components/common/BilingualText';
import { CardHead } from '@/components/common/CardAnatomy';
import { MainLandmark } from '@/components/layout/AppShell';

const LAST_UPDATED = 'October 7, 2026';
const LAST_UPDATED_EL = '7 Οκτωβρίου 2026';

const sections = [
  {
    id: 'introduction',
    title: '1. Introduction',
    icon: Shield,
    content: `CoFounderBay ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our platform.

Please read this Privacy Policy carefully. By using CoFounderBay, you consent to the data practices described in this policy. If you do not agree with the terms of this Privacy Policy, please do not access the Platform.`,
  },
  {
    id: 'information-collected',
    title: '2. Information We Collect',
    icon: Database,
    content: `We collect information in several ways:

**Information You Provide:**
• Account information (name, email, password)
• Profile information (bio, skills, experience, location)
• Communication content (messages, posts, comments)
• Payment information (processed by secure third-party providers)
• Feedback and correspondence

**Information Collected Automatically:**
• Device information (browser type, operating system)
• Usage data (pages visited, features used, time spent)
• IP address and approximate location
• Cookies and browser storage (see section 8)

**Information from Third Parties:**
• Social login providers (Google, LinkedIn, GitHub)
• SSO identity providers (for organization accounts)
• Analytics and advertising partners`,
  },
  {
    id: 'how-we-use',
    title: '3. How We Use Your Information',
    icon: Eye,
    content: `We use collected information to:

• Provide, maintain, and improve the Platform
• Create and manage your account
• Facilitate connections and matches between users
• Send notifications and updates
• Respond to inquiries and provide support
• Analyze usage patterns and optimize performance
• Detect and prevent fraud and abuse
• Comply with legal obligations
• Personalize your experience
• Send marketing communications (with your consent)

We process your data based on legitimate interests, contractual necessity, legal obligations, and your consent where applicable.`,
  },
  {
    id: 'ai-features',
    title: '4. AI Features, Matching and Verification',
    icon: Settings,
    content: `This section describes how these features behave in the software today.

**The assistant:**
• It answers from information you can already see on the Platform and proposes actions. Nothing is changed until you confirm the proposal, and each proposal says whether it can be undone.
• Its replies are generated by a language model served through Ollama, a model server run by the operator of this Platform. Conversations you keep are stored with your account.
• For each assistant request we record which feature was used, the model, how long it took and whether it succeeded. We do not record the text of the request in that log.

**Profile suggestions:**
• When the operator has enabled it, profile writing suggestions are generated with OpenAI's API. The request contains your headline, bio, location, skills and availability.

**Matching, the co-founder scout and promoted placement:**
• Match suggestions and the co-founder scout are produced by rules on your profile, your stated preferences and the "Open to" signals people choose to set. Each suggestion shows why it was made. The scout only proposes: it does not contact the people it proposes or tell them.
• Members on a paid plan may appear in a separate slot labelled "Promoted" above search results they already match. It does not change anyone's match score or the order of the other results.

**Verification and LinkedIn:**
• Work-email codes are stored hashed and expire after 15 minutes. "Verified on LinkedIn" stores only which categories LinkedIn verified (identity, workplace), never documents.
• Accounts whose role is investor or organisation need a work-email or LinkedIn workplace verification, or a role checked by the platform team, before they accept an introduction or answer an investor-introduction card.
• A LinkedIn data export you choose to import is read in your browser. If you use LinkedIn's portability API instead, the selected fields wait on our server for at most 15 minutes and are deleted when your profile form reads them. Nothing reaches your profile until you press Save.

**Safety rules and the transparency report:**
• Before two people have both confirmed, messages, notes, cards and briefs that contain contact details or promised returns are refused, not rewritten. Each refusal is recorded as its kind, where it happened and when, with no account and no text, and the counts are published per half year at /transparency together with the number of reports received and decided.

You can review your assistant preferences in Settings → AI preferences.`,
  },
  {
    id: 'information-sharing',
    title: '5. Information Sharing',
    icon: Globe,
    content: `We may share your information with:

**Other Users:**
• Profile information you choose to make public
• Messages and content you share with other users
• Connection and collaboration information

**Service Providers:**
• Cloud hosting and infrastructure providers
• Analytics and monitoring services
• Payment processors
• Email and communication services
• Customer support tools

**Legal and Safety:**
• To comply with legal obligations
• To protect our rights and property
• To prevent fraud or illegal activity
• In response to lawful requests by authorities

**Business Transfers:**
• In connection with mergers, acquisitions, or asset sales

We do not sell your personal information to third parties.`,
  },
  {
    id: 'data-security',
    title: '6. Data Security',
    icon: Lock,
    content: `We implement appropriate technical and organizational measures to protect your information:

• Encryption of data in transit (TLS/SSL)
• Encryption of sensitive data at rest
• Regular security assessments and audits
• Access controls and authentication
• Employee training on data protection
• Incident response procedures

While we strive to protect your information, no method of transmission or storage is 100% secure. We cannot guarantee absolute security.`,
  },
  {
    id: 'your-rights',
    title: '7. Your Rights',
    icon: UserCheck,
    content: `Depending on your location, you may have the following rights:

**Access:** Request a copy of your personal data
**Correction:** Request correction of inaccurate data
**Deletion:** Request deletion of your data
**Portability:** Receive your data in a portable format
**Restriction:** Request restriction of processing
**Objection:** Object to certain processing activities
**Withdrawal:** Withdraw consent at any time

To exercise these rights, contact us at privacy@cofounderbay.com or use the settings in your account.

We will respond to requests within 30 days or as required by applicable law.`,
  },
  {
    id: 'cookies',
    title: '8. Cookies and Tracking',
    icon: Settings,
    content: `We use two kinds of browser storage, and nothing else:

**Essential (always on):**
• Your sign-in session and its security (session and CSRF cookies)
• The language and theme you choose, kept in this browser

**Product analytics (only if you allow it):**
• Which pages and features are used, through PostHog on its EU host, when the Platform is configured with it
• Off until you choose "Allow analytics" in the cookie banner; choosing "Essential only", or withdrawing consent later, stops it in that browser

We do not use advertising or marketing cookies, and we do not share browsing data with advertisers.

You can change your choice at any time with "Cookie choices" in the site footer or in Settings → Privacy.`,
  },
  {
    id: 'data-retention',
    title: '9. Data Retention',
    icon: Database,
    content: `We retain your information for as long as:

• Your account is active
• Necessary to provide our services
• Required by legal obligations
• Needed for legitimate business purposes

When you delete your account:
• Profile information is removed within 30 days
• Messages may be retained for the other party
• Some data may be retained for legal compliance
• Anonymized data may be retained for analytics

You can request data deletion by contacting us or using account settings.`,
  },
  {
    id: 'international',
    title: '10. International Transfers',
    icon: Globe,
    content: `Your information may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place:

• Standard contractual clauses
• Adequacy decisions
• Binding corporate rules where applicable

By using the Platform, you consent to the transfer of your information to countries that may have different data protection laws than your jurisdiction.`,
  },
  {
    id: 'children',
    title: '11. Children\'s Privacy',
    icon: Shield,
    content: `CoFounderBay is not intended for users under 18 years of age. We do not knowingly collect personal information from children.

If we learn that we have collected information from a child under 18, we will take steps to delete that information promptly.

If you believe a child has provided us with personal information, please contact us immediately.`,
  },
  {
    id: 'changes',
    title: '12. Changes to This Policy',
    icon: Settings,
    content: `We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated revision date.

For significant changes, we will:
• Notify you via email
• Display a prominent notice on the Platform
• Require acknowledgment where appropriate

Your continued use of the Platform after changes constitutes acceptance of the updated policy.`,
  },
  {
    id: 'contact',
    title: '13. Contact Us',
    icon: Mail,
    content: `If you have questions about this Privacy Policy or our data practices, contact us:

**Email:** privacy@cofounderbay.com
**Data Protection Officer:** dpo@cofounderbay.com

**Mailing Address:**
CoFounderBay Privacy Team
[Address]

We aim to respond to all inquiries within 30 days.`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border bg-card/95 backdrop-blur-sm">
        <div className="mx-auto flex h-14 max-w-4xl items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="icon-sm" />
            {/* "CoFounderBay" alone on a phone, so the bar keeps one line. */}
            <span className="text-sm font-medium"><span className="hidden sm:inline">Back to </span>CoFounderBay</span>
          </Link>
          <div className="flex min-w-0 items-center gap-0.5 sm:gap-3">
            <Button variant="ghost" size="sm" className="min-w-0 whitespace-nowrap px-2 text-xs sm:px-3" asChild>
              <Link href="/terms"><BilingualText en="Terms of Service" el="Όροι χρήσης" compact /></Link>
            </Button>
            <Button variant="ghost" size="sm" className="min-w-0 whitespace-nowrap px-2 text-xs sm:px-3" asChild>
              <Link href="/help"><BilingualText en="Help Center" el="Κέντρο βοήθειας" compact /></Link>
            </Button>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="border-b border-border bg-muted/30">
        <div className="mx-auto max-w-4xl px-4 py-12 text-center">
          <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-muted">
            <Shield className="h-7 w-7 text-primary-accessible" />
          </div>
          <h1 className="text-3xl font-semibold text-foreground mb-2"><BilingualText en="Privacy Policy" el="Πολιτική απορρήτου" compact /></h1>
          <p className="text-sm text-muted-foreground">
            <BilingualText en={`Last updated: ${LAST_UPDATED}`} el={`Τελευταία ενημέρωση: ${LAST_UPDATED_EL}`} compact />
          </p>
          {/* Legal text is not machine-translated: a paraphrase could promise something the policy does not. */}
          <p className="mx-auto mt-3 max-w-xl text-sm text-muted-foreground">
            <BilingualText en="The policy below is written in English; the English text is the version that applies." el="Η παρακάτω πολιτική είναι γραμμένη στα Αγγλικά· ισχύει το αγγλικό κείμενο." keepSecondaryOnMobile wrap />
          </p>
        </div>
      </section>

      {/* Quick Summary */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-4xl px-4 py-8">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-4"><BilingualText en="Privacy at a Glance" el="Το απόρρητο με μια ματιά" compact /></h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {[
              { icon: Database, label: 'Data Collection', labelEl: 'Συλλογή δεδομένων', desc: 'We collect only what we need', descEl: 'Συλλέγουμε μόνο ό,τι χρειαζόμαστε' },
              { icon: Lock, label: 'Security', labelEl: 'Ασφάλεια', desc: 'Your data is encrypted', descEl: 'Τα δεδομένα σας κρυπτογραφούνται' },
              { icon: UserCheck, label: 'Your Rights', labelEl: 'Τα δικαιώματά σας', desc: 'Access, correct, delete', descEl: 'Πρόσβαση, διόρθωση, διαγραφή' },
              { icon: Trash2, label: 'No Selling', labelEl: 'Καμία πώληση', desc: 'We never sell your data', descEl: 'Δεν πουλάμε ποτέ τα δεδομένα σας' },
            ].map((item) => (
              // Four across, a side icon left ~88px for the text and the Greek
              // ran out of its tile; the icon sits above the text there.
              <div key={item.label} className="flex items-start gap-3 rounded-lg border border-border bg-card p-4 lg:flex-col lg:gap-2.5">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-muted">
                  <item.icon className="h-4 w-4 text-primary-accessible" />
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-medium text-foreground"><BilingualText en={item.label} el={item.labelEl} compact /></p>
                  <p className="text-xs text-muted-foreground"><BilingualText en={item.desc} el={item.descEl} wrap /></p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Table of Contents */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-4xl px-4 py-8">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-4"><BilingualText en="Table of Contents" el="Περιεχόμενα" compact /></h2>
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {sections.map((section) => (
              <a
                key={section.id}
                href={`#${section.id}`}
                className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
              >
                <section.icon className="h-3.5 w-3.5 shrink-0" />
                <span className="truncate">{section.title}</span>
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* Content */}
      <MainLandmark className="mx-auto max-w-4xl px-4 py-12">
        <div className="space-y-12">
          {sections.map((section) => (
            <Card key={section.id} id={section.id} className="scroll-mt-20 border-border">
              <CardContent className="space-y-4">
                <CardHead
                  titleAs="h2"
                  mark={(
                    <div data-card-mark="" className="flex h-10 w-10 items-center justify-center rounded-xl bg-muted">
                      <section.icon className="icon-md text-primary-accessible" aria-hidden="true" />
                    </div>
                  )}
                  title={section.title}
                  className="items-center"
                />
                <LegalText content={section.content} />
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Footer CTA */}
        {/* Closing note: left on one axis like every card, the two ways on
            under it. It was centred, the only centred text box on the page. */}
        <div className="mt-12 space-y-4 rounded-xl border border-border bg-muted/30 p-4 sm:p-6">
          <p className="card-body text-muted-foreground">
            <BilingualText en="Your privacy matters to us. If you have any questions, please don't hesitate to reach out." el="Το απόρρητό σας μας ενδιαφέρει. Για οποιαδήποτε ερώτηση, επικοινωνήστε μαζί μας." wrap />
          </p>
          <div className="flex flex-wrap gap-3">
            <Button variant="outline" size="sm" asChild>
              <Link href="/terms"><BilingualText en="Read Terms of Service" el="Διαβάστε τους όρους χρήσης" compact /></Link>
            </Button>
            <Button size="sm" asChild>
              <Link href="/settings"><BilingualText en="Manage Privacy Settings" el="Διαχείριση ρυθμίσεων απορρήτου" compact /></Link>
            </Button>
          </div>
        </div>
      </MainLandmark>

      {/* Footer */}
      <footer className="border-t border-border bg-card">
        <div className="mx-auto max-w-4xl px-4 py-6 text-center text-xs text-muted-foreground">
          © {new Date().getFullYear()} CoFounderBay. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
