/** Short tooltip descriptions for sidebar links — self-explanatory on first hover. */
export const NAV_LINK_DESCRIPTIONS: Record<string, string> = {
  '/dashboard/founder': 'Startup overview, readiness, and next actions',
  '/dashboard/mentor': 'Sessions, requests, and mentee activity',
  '/dashboard/investor': 'Deal flow KPIs and portfolio snapshot',
  '/dashboard/provider': 'Services, inquiries, and client work',
  '/dashboard/incubator': 'Cohorts, applications and startup milestones',
  '/readiness': 'Investor-readiness score and improvement tips',
  '/analytics': 'Your engagement and growth metrics',
  '/builder': 'Structure idea, team, market, and traction',
  '/builder/pitch-deck': 'Slide content linked to your builder',
  '/builder/applications': 'YC, Techstars, university, and grant templates in one place',
  '/research': 'Visual research and strategy canvases',
  '/milestones': 'Goals, owners, and due dates',
  '/projects': 'Side projects and startup initiatives',
  '/commitments': 'Need cards and the ladder to agreed terms',
  '/updates': 'Updates from founders you follow, and the ones you send',
  '/intros': 'Warm introductions through people you both know, with consent at every hop',
  '/scout': 'Proposes co-founders for your brief; never sends anything',
  '/fundraising': 'Investor pipeline and data room',
  '/ai': 'Your assistant: matches, research, fundraising. Changes wait for your confirmation',
  '/messages': 'Direct messages and intro requests',
  '/calendar': 'Calls, sessions, and events',
  '/mentor/sessions': 'Upcoming and past mentoring sessions',
  '/mentor/requests': 'Accept or decline mentee requests',
  '/mentor/mentees': 'People you currently mentor',
  '/mentor/availability': 'When you are bookable',
  '/mentor/profile': 'Public mentor profile and specialties',
  '/mentor/earnings': 'Session payments and history',
  '/mentor/reviews': 'Feedback from mentees',
  '/investor/scouting': 'Search startups by stage and sector',
  '/investor/pipeline': 'Deals from intro to close',
  '/investor/watchlist': 'Startups you are tracking',
  '/investor/portfolio': 'Companies you invested in',
  '/investor/analytics': 'Deal and portfolio metrics',
  '/provider/services': 'Listings you offer on the marketplace',
  '/provider/inquiries': 'Inbound leads from founders',
  '/provider/projects': 'Active client engagements',
  '/provider/reviews': 'Client feedback on your work',
  '/provider/profile': 'Public provider profile',
  '/provider/analytics': 'Performance and conversion stats',
  '/org/dashboard': 'Programs, cohorts, and portfolio',
  '/org/programs': 'Manage incubator or accelerator programs',
  '/org/cohorts': 'Batch intake and progress',
  '/org/applications': 'Review startup applications',
  '/org/startups': 'Portfolio companies in your programs',
  '/org/mentors': 'Mentors attached to your organization',
  '/org/events': 'Org-hosted events and RSVPs',
  '/org/members': 'Team and staff accounts',
  '/org/settings': 'Organization configuration',
  '/org/analytics': 'Program and cohort metrics',
  '/discover': 'Browse members with filters',
  '/matches': 'Compatibility-ranked suggestions',
  '/recommendations': 'Personalized picks for you',
  '/members': 'Full member directory',
  '/mentoring': 'Find and book mentors',
  '/investors': 'Angel and VC directory',
  '/opportunities': 'Roles and co-founder openings',
  '/groups': 'Communities and discussion spaces',
  '/events': 'Platform and community events',
  '/programs': 'Accelerators, grants, and cohorts',
  '/connections': 'Pending and active connections',
  '/shortlist': 'Profiles you saved',
  '/endorsements': 'Skills others validated for you',
  '/matches/compare': 'Compare two profiles side by side',
  '/learning': 'Courses and learning paths',
  '/marketplace': 'Legal, design, and growth services',
  '/jobs': 'Open roles at startups',
  '/help': 'Guides and support',
  '/feed': 'Activity from your network',
  '/activity': 'Your recent actions',
  '/achievements': 'Badges and XP progress',
  '/profile': 'How others see you',
  '/notifications': 'Alerts and updates',
  '/settings': 'Account, privacy, and billing',
  '/invite': 'Refer friends and grow the network',
  '/admin': 'Platform health and admin tools',
  '/admin/users': 'Search and moderate accounts',
  '/admin/user-management': 'Bulk user admin and verification',
  '/admin/analytics': 'Global platform metrics',
  '/admin/communities': 'Community oversight',
  '/admin/reports': 'User reports and flags',
  '/tenant/dashboard': 'White-label tenant overview',
  '/tenant/branding': 'Logo, colors, and landing copy',
  '/tenant/sso': 'Enterprise sign-on setup',
  '/tenant/domains': 'Custom domain mapping',
  '/tenant/members': 'Users in your tenant',
  '/tenant/programs': 'Tenant-scoped programs',
  '/admin/audit-log': 'Who changed what, and when',
  '/admin/automations': 'Rules that run without manual review',
  '/admin/billing': 'Revenue, invoices and subscriptions',
  '/admin/dashboard': 'Users, activity and what waits on you',
  '/admin/domains': 'Verify and route custom domains',
  '/admin/feature-flags': 'Roll features out or back without a deploy',
  '/admin/programs': 'Approve, pause or audit programs',
  '/admin/sso': 'Enterprise sign-in for organisations',
  '/admin/taxonomy': 'Skills, industries and stages that matching reads',
  '/admin/tenants': 'Create, suspend and inspect organisations',
  '/coaching': 'Book time with mentors',
  '/compare': 'Compare profiles side by side',
  '/dashboard': 'Opens the dashboard for your role',
  '/expert-reviews': 'Expert feedback on pitch, financials and strategy',
  '/profile/edit': 'Photo, bio, skills and visibility',
  '/referrals': 'Rewards when friends you invite join',
  '/reputation': 'Your trust and credibility here',
  '/saved-searches': 'Saved filters that tell you about new results',
  '/search': 'People, jobs, events, programs and posts',
  '/settings/ai': 'The model and agent that answer you',
  '/settings/billing': 'Your plan and where invoices go',
  '/settings/data-export': 'Download your profile, messages and activity',
  '/settings/notifications': 'Which emails reach you, and how often',
  '/tenant/analytics': 'Member growth, engagement and programs',
  '/tenant/api-keys': 'Scoped access for your own tools',
  '/tenant/automation': 'Triggers, conditions and actions',
  '/tenant/billing': 'Plan, seats, invoices and payment',
  '/tenant/settings': 'Membership policy and email preferences',
  '/tenant/webhooks': 'Send events to Slack, Zapier or any endpoint',
};

export function getNavDescription(href: string): string | undefined {
  return NAV_LINK_DESCRIPTIONS[href];
}
