import { createRequire } from 'node:module';
const { chromium } = createRequire(new URL('../package.json', import.meta.url))('@playwright/test');
const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
await ctx.addCookies([{ name: 'cfb_session', value: 'probe', domain: 'localhost', path: '/' },{ name: 'cfb_primary_role', value: 'founder', domain: 'localhost', path: '/' }]);
await ctx.addInitScript(({ theme }) => { localStorage.setItem('user', JSON.stringify({ id: 'u_1', role: 'founder' })); localStorage.setItem('cfb_demo_data','1'); localStorage.setItem('cfb_cookie_consent','true'); if (theme) localStorage.setItem('theme', theme); }, { theme: process.env.THEME || '' });
const p = await ctx.newPage(); const msgs = [];
p.on('console', (m) => { if (['error', 'warning'].includes(m.type())) msgs.push(m.type() + ': ' + m.text().slice(0, 300)); });
p.on('pageerror', (e) => msgs.push('pageerror: ' + e.message.slice(0, 300)));
await p.goto('http://localhost:3000/' + (process.env.ROUTE || 'projects'), { waitUntil: 'networkidle' }); await p.waitForTimeout(1500);
console.log(msgs.join('\n') || 'no console errors');
await b.close();
